const dummyNotification: Array<{[key: string]: any}> = [
    {
      "id": 1,
      "partyId": 1,
      "partyName": "등 긁어주실 분",
      "content": "apply",
      "userName": "아잠만",
      "isRead": true,
      "createdAt": new Date('12/21/2021'),
    },
    {
      "id": 2,
      "partyId": 3,
      "partyName": "이런 파티",
      "content": "accept",
      "isRead": true,
      "createdAt": new Date('12/21/2021'),
    },
    {
      "id": 3,
      "partyId": 4,
      "partyName": "저런 파티",
      "content": "deny",
      "isRead": true,
      "createdAt": new Date('12/22/2021'),
    },
    {
      "id": 4,
      "partyId": 3,
      "partyName": "이런 파티",
      "content": "expel",
      "isRead": true,
      "createdAt": new Date('12/23/2021'),
    },
    {
      "id": 5,
      "partyId": 1,
      "partyName": "등 긁어주실 분",
      "content": "favorite",
      "userName": "케첩",
      "isRead": true,
      "createdAt": new Date('12/23/2021'),
    },
    {
      "id": 6,
      "partyId": 2,
      "partyName": "이러저런 파티",
      "content": "complete",
      "isRead": true,
      "createdAt": new Date('12/24/2021'),
    },
    {
      "id": 7,
      "partyId": 3,
      "partyName": "이런 파티",
      "content": "fullparty",
      "isRead": true,
      "createdAt": new Date('12/24/2021'),
    },
    {
      "id": 8,
      "partyId": 3,
      "partyName": "이런 파티",
      "content": "reparty",
      "isRead": true,
      "createdAt": new Date('12/25/2021'),
    },
    {
      "id": 9,
      "partyId": 3,
      "partyName": "이런 파티",
      "content": "dismiss",
      "isRead": true,
      "createdAt": new Date('12/25/2021'),
    },
    {
      "id": 10,
      "partyId": 1,
      "partyName": "등 긁어주실 분",
      "content": "question",
      "userName": "앤",
      "isRead": true,
      "createdAt": new Date('12/25/2021'),
    },
    {
      "id": 11,
      "partyId": 5,
      "partyName": "요런파티",
      "content": "answer",
      "isRead": false,
      "createdAt": new Date('12/26/2021'),
    },
    {
      "id": 12,
      "content": "levelup",
      "level": 7,
      "isRead": false,
      "createdAt": new Date('12/26/2021'),
    },
  ];

export default dummyNotification;